-- weglow.uz payments: product catalog + every payment attempt (Multicard / Rahmat and Uzum Nasiya).
-- Only the `pay` Edge Function (service role) touches these tables; RLS is on with no policies.

create table if not exists public.uz_products (
  id                text primary key,              -- 'marine', 'vitc'
  name_ru           text not null,
  name_uz           text not null,
  price_uzs         bigint,                        -- price in sum; null = not for online sale yet
  mxik              text,                          -- ИКПУ from tasnif.soliq.uz (required for fiscal receipts)
  package_code      text,                          -- package code from tasnif.soliq.uz
  vat_percent       integer,                       -- null if the company is not a VAT payer
  nasiya_product_id integer,                       -- numeric product id sent to Uzum Nasiya
  nasiya_category   integer,                       -- category id given by the Uzum Nasiya manager
  nasiya_unit_id    integer default 1,             -- unit type given by the Uzum Nasiya manager
  active            boolean not null default true,
  sort              integer not null default 0,
  updated_at        timestamptz not null default now()
);

insert into public.uz_products (id, name_ru, name_uz, nasiya_product_id, sort) values
  ('marine', 'WEGLOW Marine Collagen (30 саше)',             'WEGLOW Marine Collagen (30 ta sashe)',             1, 1),
  ('vitc',   'WEGLOW Marine Collagen + Vitamin C (30 саше)', 'WEGLOW Marine Collagen + Vitamin C (30 ta sashe)', 2, 2)
on conflict (id) do nothing;

create table if not exists public.uz_payments (
  id                 uuid primary key default gen_random_uuid(),
  number             bigint generated by default as identity (start with 1001) unique, -- shown to clients as WG-1001
  created_at         timestamptz not null default now(),
  updated_at         timestamptz not null default now(),
  source             text not null check (source in ('site', 'manager')),
  provider           text not null check (provider in ('multicard', 'nasiya')),
  status             text not null default 'new'
                     check (status in ('new', 'pending', 'paid', 'cancelled', 'failed')),
  product_id         text not null references public.uz_products (id),
  qty                integer not null check (qty between 1 and 99),
  amount_uzs         bigint not null,              -- price × qty, without Nasiya markup
  customer_name      text,
  customer_phone     text,
  city               text,
  lang               text not null default 'ru',
  created_by         text,                         -- manager label for manual invoices
  -- Multicard
  mc_uuid            text unique,
  checkout_url       text,
  short_link         text,
  receipt_url        text,
  ps                 text,                         -- uzcard / humo / visa / payme / click / uzum ...
  card_pan           text,
  -- Uzum Nasiya
  nasiya_buyer_id    bigint,
  nasiya_order_id    bigint,                       -- internal id used by confirm / cancel
  nasiya_contract_id bigint,                       -- contract number used by check-status
  nasiya_period      text,
  nasiya_total       numeric,                      -- what the client pays incl. Nasiya markup
  paid_at            timestamptz,
  error              text
);

create index if not exists uz_payments_created_idx on public.uz_payments (created_at desc);
create unique index if not exists uz_payments_nasiya_order_idx on public.uz_payments (nasiya_order_id) where nasiya_order_id is not null;

alter table public.uz_products enable row level security;
alter table public.uz_payments enable row level security;
